# Use the file format compatible with Docker Compose 3.8
version: "3.3"

# Each thing that Docker Compose runs is referred to as
# a "service". In our case, our Rails application is one
# service ("web") and our PostgreSQL database instance
# is another service ("database").
services:
  poke_trader_calculator:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./.:/var/www/poke_trader_calculator
      - "/etc/localtime:/etc/localtime:ro"
      - .:/code:cached
    environment:
      RAILS_ENV: development

  tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "bundle exec rspec"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: test

  db:
    # instead of building it from zero we'll use an existent image (see docker hub)
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"

volumes:
  db_data:
