# Use the file format compatible with Docker Compose 3.8
version: "3.3"

# Each thing that Docker Compose runs is referred to as
# a "service". In our case, our Rails application is one
# service ("web") and our PostgreSQL database instance
# is another service ("database").
services:

  db:
    # instead of building it from zero we'll use an existent image (see docker hub)
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"

  web:
    # The root directory from which we're building.
    build: .

    # This makes it so any code changes inside the project
    # directory get synced with Docker. Without this line,
    # we'd have to restart the container every time we
    # changed a file.
    volumes:
      - .:/code:cached

    # The command to be run when we run "docker-compose up".
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    # Expose port 3000.
    ports:
      - "3000:3000"

    depends_on:
      - db

    # Specify the values of the environment variables
    # used in this container.
    environment:
      RAILS_ENV: development

# Declare the volumes that our application uses.
volumes:
  db_data: